name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: archtenet/platform-infra/.github/workflows/service-ci.yml@main
    with:
      service-name: ws-gateway
      helm-path: ws-gateway/helm
    secrets: inherit
